version: '2'

services:
  data:
    image: busybox
    volumes:
      - ../authenticate:/authenticate
      - ../authorize:/authorize
      - ../users:/users
  webserver:
    extends:
      file: ./docker/nginx/docker-compose.yml
      service: webserver
    container_name: erdiko_users_web
    volumes_from: [data]
    ports:
      - "8088:80"
  php:
    extends:
      file: ./docker/php/7.0/docker-compose.yml
      service: php
    container_name: erdiko_users_php
    volumes_from: [data]
    extra_hosts:
     - "docker.local:172.17.0.1"
  db:
    container_name: erdiko_users_db
    env_file: ./docker/mysql/environment.env
    image: mysql:latest
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3301:3306"
