version: '2'

services:
  webserver:
    container_name: erdiko_users_nginx
    image: nginx:latest
    env_file: environment.env
    volumes:
      - .:/code
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/site.conf
      - ./docker/nginx/fastcgi.conf:/etc/nginx/fastcgi.conf
    ports:
      - "8088:80"
  php:
    container_name: erdiko_users_php
    env_file: environment.env
    image: erdiko_php7fpm
    build:
      context: ./docker/php7
    volumes:
      - .:/code
      - ./docker/php7/conf.d:/usr/local/etc/php/conf.d
  db:
    container_name: erdiko_users_db
    env_file: ./docker/mysql/environment.env
    image: mysql:latest
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3306:3306"
